import './globals.css'
import 'react-toastify/dist/ReactToastify.css'
import { Roboto } from 'next/font/google'
import Toaster from '../../lib/Toaster'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
const roboto = Roboto({
  weight: ['100', '300', '400', '500', '700', '900'],
  subsets: ['latin'],
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en' className={`${roboto.className} `}>
      <body>
        {children}
        <Toaster />
      </body>
    </html>
  )
}
