import './globals.css'
import 'react-toastify/dist/ReactToastify.css'

import { Roboto } from 'next/font/google'
import Toaster from '../../lib/Toaster'
import { CustomerIntakeFormContextProvider } from '../../context/CustomerIntakeFormContext'
import { Providers } from './providers/nextauthProvider'
import Stepper from '@/components/Stepper'
import { StepperContextContextProvider } from '../../context/StepperContext'
export const metadata = {
  title: 'TalentPop',
  description: 'Generated by create next app',
}
const roboto = Roboto({
  weight: ['100', '300', '400', '500', '700', '900'],
  subsets: ['latin'],
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en' className={`${roboto.className} `}>
      <body>
        <Providers>
          <StepperContextContextProvider>
            <CustomerIntakeFormContextProvider>
              {children}
            </CustomerIntakeFormContextProvider>
          </StepperContextContextProvider>
        </Providers>
        <Toaster />
      </body>
    </html>
  )
}
